export {default as Contact} from "./Contact"
export {default as Description} from "./Description.js"
export {default as Hero} from "./Hero"
export {default as Skills} from "./Skills"
export {default as Portfolio} from "./Portfolio"
